# Generated by Django 6.0 on 2025-12-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
